print("Abdullah")
print("hello word")
print("Abdullah Amir")
print("1,2,3")
print("hello\nworld")
print("hello\tword")
print("Aplle,Bnana,Cherry")
print("1-2-3")
print("Hello word")
print("12")
print('"hello!"')
print("\.")
print("I am 20 years old")
print("The number is 5")
print("1\n2\n3\n4\n5")
